
const arrCategory = [
  'Clothing',
  'Footwear',
  'Accessories',
  'Watches',
  'Sports & Fiteness',
  'Mobiles',
  'TV',
  'Books',
  'Jewellery',
  'Clocks',
  'Bags',
  'Grooming & Perfumes',
]

const brd=[
  'Adidas',
  'Allen Solly',
  'SkyBags',
  'Backberrys',
  'Campus',
  'Highlander',
  'HRX by Hrithik Roshan',
  'Indian Terrain',
  'Jack Jones',
  'Jockey',
  'Lee',
  'Levi\'s',
  'Nike',
  'Park Avenue',
  'Samsung',
  'Apple',
  'Titen',
  'Wild Stone',
  'Adil Qadri',
  'Realme'
]

const arrImg = [
  'src/assets/sho1.webp',
  'src/assets/sho2.webp',
  'src/assets/sho3.webp',
  'src/assets/sho4.webp',
  'src/assets/sho5.webp',
  'src/assets/sho6.webp',
  'src/assets/ts1.webp',
  'src/assets/ts2.webp',
  'src/assets/ts3.webp',
  'src/assets/ts4.webp',
  'src/assets/ts5.webp',
  'src/assets/per1.webp',
  'src/assets/per2.webp',
  'src/assets/per3.webp',
  'src/assets/per4.webp',
  'src/assets/per5.webp',
  'src/assets/w1.webp',
  'src/assets/w2.webp',
  'src/assets/w3.webp',
  'src/assets/w4.webp',
  'src/assets/w5.webp',
  'src/assets/sit1.webp',
  'src/assets/sit2.webp',
  'src/assets/sit3.webp',
  'src/assets/sit4.webp',
  'src/assets/sit5.webp',
  'src/assets/jen1.webp',
  'src/assets/jen2.webp',
  'src/assets/jen3.webp',
  'src/assets/jen4.webp',
  'src/assets/jen5.webp',
  'src/assets/bac1.webp',
  'src/assets/bac2.webp',
  'src/assets/bac3.webp',
  'src/assets/bac4.webp',
  'src/assets/bac5.webp',
  'src/assets/jen6.webp',
  'src/assets/jen7.webp',
  'src/assets/jen8.webp',
  'src/assets/jen9.webp',
  'src/assets/jen10.webp',
  'src/assets/mob1.webp',
  'src/assets/mob2.webp',
  'src/assets/mob3.webp',
  'src/assets/mob4.webp',
  'src/assets/mob5.webp',
  'src/assets/sho11.webp',
  'src/assets/sho12.webp',
  'src/assets/sho8.webp',
  'src/assets/sho9.webp',
  'src/assets/sho10.webp',
  'src/assets/spt1.webp',
  'src/assets/spt2.webp',
  'src/assets/spt3.webp',
  'src/assets/spt4.webp',
  'src/assets/spt5.webp',
  'src/assets/np1.webp',
  'src/assets/np2.webp',
  'src/assets/np3.webp',
  'src/assets/per7.webp',
  'src/assets/per8.webp',
  'src/assets/per9.webp',




]
const shoppingItems = [
  {
    image:arrImg[47],
    id: 1,
    name: 'Formal Shoes',
    price: 699,
    oldPrice:350,
    category: arrCategory[1],
    brand:brd[0],
  },
  {
    image:arrImg[29],
    id: 2,
    name: 'Jeans',
    price: 839.99,
    category: arrCategory[0],
    brand:brd[3],
  },
  {
    image:arrImg[ 1],
    id: 3,
    name: 'Running Shoes',
    price: 979.99,
    category: arrCategory[1],
    brand:brd[4],
  },
  {
    image:arrImg[32 ],
    id: 4,
    name: 'Backpack',
    price: 859.99,
    category: arrCategory[2],
    brand:brd[2],
  },
  {
    image:arrImg[ 3],
    id: 5,
    name: 'Sports Shoes',
    price: 1249.99,
    category: arrCategory[1],
    brand:brd[12],
  },
  {
    image:arrImg[ 27],
    id:6,
    name: 'Trousers Pants',
    price: 649.99,
    category: arrCategory[0],
    brand:brd[7],
  },
  {
    image:arrImg[ 28],
    id: 7,
    name: 'Formal Trousers',
    price: 739.99,
    category: arrCategory[0],
    brand:brd[5],
  },
  {
    image:arrImg[59 ],
    id: 8,
    name: 'Men\'s Perfume',
    price: 149.99,
    category: arrCategory[11],
    brand:brd[13],
  },
  {
    image:arrImg[21],
    id: 9,
    name: 'Shirt',
    price: 299.99,
    category: arrCategory[0],
    brand:brd[8],
  },
  {
    image:arrImg[58],
    id: 10,
    name: 'Track Pants',
    price: 539.99,
    category: arrCategory[4],
    brand:brd[6],
  },

  {
    image:arrImg[24],
    id: 11,
    name: 'Formal Shirt',
    price: 249.99,
    category: arrCategory[0],
    brand:brd[9],
  },
  {
    image:arrImg[30],
    id: 12,
    name: 'Jeans',
    price: 829.99,
    category: arrCategory[0],
    brand:brd[8],
  },
  {
    image:arrImg[8],
    id: 13,
    name: 'T-shirt',
    price: 299,
    oldPrice:350,
    category: arrCategory[0],
    brand:brd[0],

  },
  {
    image:arrImg[26],
    id: 14,
    name: 'Jeans',
    price: 739.99,
    category: arrCategory[0],
    brand:brd[9],
  },
  {
    image:arrImg[2],
    id: 15,
    name: 'Running Shoes',
    price: 1579.99,
    category: arrCategory[1],
    brand:brd[12],
  },
  {
    image:arrImg[54],
    id: 16,
    name: 'Dumbbells',
    price: 2939.99,
    category: arrCategory[4],
    brand:brd[0],
  },
  
  {
    image:arrImg[10],
    id: 17,
    name: 'T-Shirt',
    price: 349.99,
    category: arrCategory[0],
    brand:brd[6],
  },
  {
    image:arrImg[20],
    id:18,
    name: 'Watch',
    price: 219.99,
    category: arrCategory[3],
    brand:brd[16],
  },
  {
    image:arrImg[6],
    id: 19,
    name: 'T-shirt',
    price: 299,
    oldPrice:350,
    category: arrCategory[0],
    brand:brd[5],

  },
  {
    image:arrImg[36],
    id: 20,
    name: 'Jeans',
    price: 439.99,
    category: arrCategory[0],
    brand:brd[3],
  },
  {
    image:arrImg[5],
    id: 21,
    name: 'Classic Shoes',
    price: 1279.99,
    category: arrCategory[1],
    brand:brd[4],
  },
  {
    image:arrImg[34],
    id: 22,
    name: 'Backpack',
    price: 239.99,
    category: arrCategory[2],
    brand:brd[2],
  },
  {
    image:arrImg[37],
    id: 23,
    name: 'Jeans',
    price: 1149.99,
    category: arrCategory[0],
    brand:brd[6],
  },
  {
    image:arrImg[39],
    id:24,
    name: 'Trousers',
    price: 749.99,
    category: arrCategory[0],
    brand:brd[7],
  },
  {
    image:arrImg[42],
    id: 25,
    name: 'Mobile',
    price: 39999.99,
    category: arrCategory[5],
    brand:brd[14],
  },
  {
    image:arrImg[61],
    id: 26,
    name: 'Womens Perfume',
    price: 149.99,
    category: arrCategory[11],
    brand:brd[13],
  },
  {
    image:arrImg[7],
    id: 27,
    name: 'T-Shirt',
    price: 699.99,
    category: arrCategory[0],
    brand:brd[8],
  },
  {
    image:arrImg[45],
    id: 28,
    name: 'IPhone12',
    price: 89990.99,
    category: arrCategory[5],
    brand:brd[15],
  },
  {
    image:arrImg[55],
    id: 29,
    name: 'Elastic Bands',
    price: 439.99,
    category: arrCategory[4],
    brand:brd[12],
  },

  {
    image:arrImg[22],
    id: 30,
    name: 'Shirt',
    price: 499.99,
    category: arrCategory[0],
    brand:brd[8],
  },
  {
    image:arrImg[36],
    id: 31,
    name: 'Pants',
    price: 1189.99,
    category: arrCategory[0],
    brand:brd[3],
  },
  {
    image:arrImg[16],
    id: 32,
    name: 'Rist Watch',
    price: 449.99,
    category: arrCategory[3],
    brand:brd[16],
  },
  {
    image:arrImg[0],
    id: 33,
    name: 'Formal Shoes',
    price: 1139.99,
    category: arrCategory[1],
    brand:brd[9],
  },
  {
    image:arrImg[56],
    id: 34,
    name: 'Track Pants',
    price: 739.99,
    category: arrCategory[4],
    brand:brd[0],
  },

  {
    image:arrImg[38],
    id: 35,
    name: 'Jeans',
    price: 839.99,
    category: arrCategory[0],
    brand:brd[3],
  },
  {
    image:arrImg[49],
    id: 36,
    name: 'Running Shoes',
    price: 979.99,
    category: arrCategory[1],
    brand:brd[4],
  },
  {
    image:arrImg[35],
    id: 37,
    name: 'Backpack',
    price: 1599.99,
    category: arrCategory[2],
    brand:brd[2],
  },
  {
    image:arrImg[50],
    id: 38,
    name: 'Formal Shoes',
    price: 1149.99,
    category: arrCategory[1],
    brand:brd[6],
  },
  {
    image:arrImg[57],
    id:39,
    name: 'Elastic Pants',
    price: 549.99,
    category: arrCategory[4],
    brand:brd[12],
  },
  
  {
    image:arrImg[12],
    id: 40,
    name: 'Perfume',
    price: 149.99,
    category: arrCategory[11],
    brand:brd[17],
  },
  {
    image:arrImg[4],
    id: 41,
    name: 'Running Shoes',
    price: 1399.99,
    category: arrCategory[1],
    brand:brd[8],
  },
  
  {
    image:arrImg[60],
    id: 42,
    name: 'Saint',
    price: 149.99,
    category: arrCategory[11],
    brand:brd[13],
  },
  {
    image:arrImg[18],
    id: 43,
    name: 'Watch',
    price: 299,
    oldPrice:350,
    category: arrCategory[3],
    brand:brd[16],

  },
  {
    image:arrImg[53],
    id: 44,
    name: 'Running Machine',
    price: 9999.99,
    category: arrCategory[4],
    brand:brd[12],
  },
{
    image:arrImg[51],
    id: 45,
    name: 'Gym Ball',
    price: 539.99,
    category: arrCategory[4],
    brand:brd[0],
  },
  {
    image:arrImg[11],
    id: 46,
    name: 'Perfume',
    price: 159.99,
    category: arrCategory[11],
    brand:brd[18],
  },
  {
    image:arrImg[31],
    id: 47,
    name: 'Backpack',
    price: 439.99,
    category: arrCategory[2],
    brand:brd[2],
  },
  {
    image:arrImg[33],
    id: 48,
    name: 'Classic Backpack',
    price: 789.99,
    category: arrCategory[0],
    brand:brd[3],
  },
  {
    image:arrImg[19],
    id: 49,
    name: 'Rist Watch',
    price: 649.99,
    category: arrCategory[3],
    brand:brd[16],
  },
  {
    image:arrImg[43],
    id: 50,
    name: 'Mobile',
    price: 14999.99,
    category: arrCategory[5],
    brand:brd[19],
  },  


  // Add more items as needed
];

export default shoppingItems